=== gbv/avram-js/avram-schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "additionalProperties": false,
  "definitions": {
    "codelist": {
      "oneOf": [
        {
          "$ref": "#/definitions/non-empty-string"
        },
        {
          "$ref": "#/definitions/explicitcodelist"
        }
      ]
    },
    "explicitcodelist": {
      "additionalProperties": false,
      "patternProperties": {
        "^.+$": {
          "oneOf": [
            {
              "additionalProperties": false,
              "properties": {
                "code": {
                  "type": "string"
                },
                "created": {
                  "$ref": "#/definitions/timestamp"
                },
                "deprecated": {
                  "type": "boolean"
                },
                "description": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                },
                "modified": {
                  "$ref": "#/definitions/timestamp"
                }
              },
              "type": "object"
            },
            {
              "type": "string"
            }
          ]
        }
      },
      "type": "object"
    },
    "field-schedule": {
      "additionalProperties": false,
      "patternProperties": {
        "^.+$": {
          "additionalProperties": false,
          "properties": {
            "codes": {
              "$ref": "#/definitions/codelist"
            },
            "counter": {
              "pattern": "^[0-9]+(-[0-9]+)?$",
              "type": "string"
            },
            "created": {
              "$ref": "#/definitions/timestamp"
            },
            "deprecated": {
              "type": "boolean"
            },
            "description": {
              "type": "string"
            },
            "indicator1": {
              "$ref": "#/definitions/indicator"
            },
            "indicator2": {
              "$ref": "#/definitions/indicator"
            },
            "label": {
              "type": "string"
            },
            "modified": {
              "$ref": "#/definitions/timestamp"
            },
            "occurrence": {
              "pattern": "^[0-9][0-9](-[0-9][0-9])?$",
              "type": "string"
            },
            "pattern": {
              "$ref": "#/definitions/regex"
            },
            "pica3": {
              "type": "string"
            },
            "positions": {
              "$ref": "#/definitions/positions"
            },
            "records": {
              "$ref": "#/definitions/non-negative-integer"
            },
            "repeatable": {
              "type": "boolean"
            },
            "required": {
              "type": "boolean"
            },
            "rules": {
              "$ref": "#/definitions/rules"
            },
            "subfields": {
              "$ref": "#/definitions/subfield-schedule"
            },
            "tag": {
              "$ref": "#/definitions/non-empty-string"
            },
            "total": {
              "$ref": "#/definitions/non-negative-integer"
            },
            "types": {
              "patternProperties": {
                "^.+$": {
                  "$ref": "#/definitions/typed-field-definition",
                  "type": "object"
                }
              },
              "type": "object"
            },
            "url": {
              "$ref": "#/definitions/url"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "field-types": {
      "oneOf": [
        {
          "additionalProperties": false,
          "patternProperties": {
            "^.*$": {
              "additionalProperties": false,
              "properties": {
                "positions": {
                  "$ref": "#/definitions/positions"
                }
              },
              "required": [
                "positions"
              ],
              "type": "object"
            }
          },
          "type": "object"
        },
        {
          "additionalProperties": false,
          "patternProperties": {
            "^.*$": {
              "additionalProperties": false,
              "properties": {
                "subfields": {
                  "$ref": "#/definitions/subfield-schedule"
                }
              },
              "required": [
                "subfields"
              ],
              "type": "object"
            }
          },
          "type": "object"
        }
      ]
    },
    "indicator": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "additionalProperties": false,
          "properties": {
            "codes": {
              "$ref": "#/definitions/codelist"
            },
            "description": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "pattern": {
              "$ref": "#/definitions/regex"
            },
            "url": {
              "$ref": "#/definitions/url"
            }
          },
          "type": "object"
        }
      ]
    },
    "non-empty-string": {
      "minLength": 1,
      "type": "string"
    },
    "non-negative-integer": {
      "minimum": 0,
      "type": "integer"
    },
    "positions": {
      "additionalProperties": false,
      "patternProperties": {
        "^[0-9]+(-[0-9]+)?$": {
          "additionalProperties": false,
          "properties": {
            "codes": {
              "$ref": "#/definitions/codelist"
            },
            "flags": {
              "$ref": "#/definitions/codelist"
            },
            "description": {
              "type": "string"
            },
            "end": {
              "$ref": "#/definitions/non-negative-integer"
            },
            "label": {
              "type": "string"
            },
            "pattern": {
              "$ref": "#/definitions/regex"
            },
            "start": {
              "$ref": "#/definitions/non-negative-integer"
            },
            "url": {
              "$ref": "#/definitions/url"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "regex": {
      "$ref": "#/definitions/non-empty-string"
    },
    "rules": {
      "items": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "object"
          }
        ]
      },
      "type": "array"
    },
    "subfield-schedule": {
      "additionalProperties": false,
      "patternProperties": {
        "^.*$": {
          "properties": {
            "code": {
              "type": "string"
            },
            "codes": {
              "$ref": "#/definitions/codelist"
            },
            "created": {
              "$ref": "#/definitions/timestamp"
            },
            "deprecated": {
              "type": "boolean"
            },
            "description": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "modified": {
              "$ref": "#/definitions/timestamp"
            },
            "order": {
              "description": "deprecated since 0.9.2",
              "type": "integer"
            },
            "pica3": {
              "type": "string"
            },
            "positions": {
              "$ref": "#/definitions/positions"
            },
            "records": {
              "$ref": "#/definitions/non-negative-integer"
            },
            "repeatable": {
              "type": "boolean"
            },
            "required": {
              "type": "boolean"
            },
            "rules": {
              "$ref": "#/definitions/rules"
            },
            "total": {
              "$ref": "#/definitions/non-negative-integer"
            },
            "url": {
              "$ref": "#/definitions/url"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "timestamp": {
      "type": "string"
    },
    "typed-field-definition": {
      "additionalProperties": false,
      "properties": {
        "codes": {
          "$ref": "#/definitions/codelist"
        },
        "description": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "pattern": {
          "$ref": "#/definitions/regex"
        },
        "positions": {
          "$ref": "#/definitions/positions"
        },
        "url": {
          "$ref": "#/definitions/url"
        }
      },
      "type": "object"
    },
    "url": {
      "format": "uri",
      "pattern": "^https?://",
      "type": "string"
    }
  },
  "description": "JSON Schema of Avram Schema Format to validata Avram Schemas",
  "properties": {
    "$schema": {
      "format": "uri",
      "type": "string"
    },
    "codelists": {
      "additionalProperties": false,
      "patternProperties": {
        "^.+$": {
          "anyOf": [
            {
              "$ref": "#/definitions/explicitcodelist",
              "description": "deprecated since 0.9.2"
            },
            {
              "additionalProperties": false,
              "properties": {
                "codes": {
                  "$ref": "#/definitions/explicitcodelist"
                },
                "created": {
                  "$ref": "#/definitions/timestamp"
                },
                "description": {
                  "type": "string"
                },
                "modified": {
                  "$ref": "#/definitions/timestamp"
                },
                "title": {
                  "type": "string"
                },
                "url": {
                  "$ref": "#/definitions/url"
                }
              },
              "required": [
                "codes"
              ],
              "type": "object"
            }
          ]
        }
      },
      "type": "object"
    },
    "created": {
      "$ref": "#/definitions/timestamp"
    },
    "description": {
      "type": "string"
    },
    "family": {
      "$ref": "#/definitions/non-empty-string"
    },
    "fields": {
      "$ref": "#/definitions/field-schedule"
    },
    "language": {
      "pattern": "^[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*$",
      "type": "string"
    },
    "modified": {
      "$ref": "#/definitions/timestamp"
    },
    "profile": {
      "format": "uri",
      "type": "string"
    },
    "records": {
      "$ref": "#/definitions/non-negative-integer"
    },
    "rules": {
      "$ref": "#/definitions/rules"
    },
    "title": {
      "type": "string"
    },
    "url": {
      "$ref": "#/definitions/url"
    }
  },
  "required": [
    "fields"
  ],
  "title": "Avram Schema Format",
  "type": "object"
}

=== gbv/avram-js/pages/k10plus-zentral-marc.json
{
  "title": "MARC Export für K10plus-Zentral - Vorgaben",
  "url": "https://info.gbv.de/pages/viewpage.action?pageId=894500927",
  "description": "Subset of MARC profile used for import records into K10plus-Zentral",
  "family": "marc",
  "fields": {
    "711": {
      "label": "Added Entry-Meeting Name",
      "repeatable": true,
      "indicator1": { "codes": { "2": {} } },
      "indicator2": { "codes": { "9": {} } },
      "subfields": {
        "a": {
          "label": "Meeting name or jurisdiction name as entry element",
          "repeatable": false,
          "required": true
        },
        "e": {
          "label": "Subordinate unit",
          "repeatable": true
        },
        "n": {
          "label": "Number of part/section/meeting",
          "repeatable": true
        },
        "c": {
          "label": "Location of meeting",
          "repeatable": true
        },
        "d": {
          "label": "Date of meeting or treaty signing",
          "repeatable": true
        }
      }
    },
    "720": {
      "label": "Added Entry-Uncontrolled Name",
      "repeatable": true,
      "indicator1": null,
      "indicator2": { "codes": { "9": {} } },
      "subfields": {
        "a": {
          "label": "Name",
          "repeatable": false
        }
      }
    },
    "912": {
      "label": "Internal Library Number / System flag / Product code / Holding information / OLC-SSG segment / OLC-OPC-Segment / ISIL_DE / GBV_KXP / GBV_OLC",
      "repeatable": "true",
      "subfields": {
        "a": {
          "label": "useflag / sysflag / product code / ILN / SSG segment / OPC-Segment / ISIL / GBV_KXP / GBV_OLC",
          "repeatable": false,
          "required": true,
          "pattern": "^(GBV_USEFLAG_.+|SYSFLAG_.+|.*|GBV_ILN_.+|FID|SSG-OLC-.+|SSG-OPC-.+|ISI-DE-.+|GBV_KXP|GBV_OLC)$"
        },
        "b": {
          "label": "license year for product code (if $a is product code)",
          "repeatable": false
        }
      }
    },
    "951": {
      "label": "Structure of Element",
      "repeatable": true,
      "subfields": {
        "a": {
          "label": "code",
          "required": true,
          "codes": {
            "JT": { "label": "Journal Title" },
            "AI": { "label": "Article included in other work (german: beigefügt)" },
            "AR": { "label": "Article" },
            "MC": { "label": "Multi Volume: Collective Title" },
            "MV": { "label": "Multi Volume: Volume" },
            "ST": { "label": "Serial Title" },
            "JV": { "label": "Journal Volume" },
            "BO": { "label": "single element, e.g. book" }
          }
        },
        "b": {
          "label": "code",
          "repeatable": false,
          "codes": {
            "SLoT": { "label": "Zusammenstellung ohne übergeordneten Titel" }
          }
        }
      }
    },
    "952": {
      "label": "Article source or license period",
      "repeatable": false,
      "subfields": {
        "d": {
          "label": "volume",
          "repeatable": false
        },
        "j": {
          "label": "year",
          "repeatable": false
        },
        "e": {
          "label": "issue",
          "repeatable": false
        },
        "b": {
          "label": "day",
          "repeatable": false
        },
        "c": {
          "label": "month",
          "repeatable": false
        },
        "f": {
          "label": "special issue",
          "repeatable": false
        },
        "h": {
          "label": "pages",
          "repeatable": false
        },
        "g": {
          "label": "number of pages",
          "repeatable": false
        },
        "y": {
          "label": "presentation form",
          "repeatable": false
        }
      }
    },
    "953": {
      "label": "DDC-Expansion",
      "repeatable": false,
      "subfields": {
        "2": {
          "label": "number source"
        },
        "a": {
          "label": "classification number",
          "repeatable": true
        },
        "u": {
          "label": "URL",
          "repeatable": false
        }
      }
    },
    "980": {
      "label": "Library Holding",
      "repeatable": true
    },
    "981": {
      "label": "Library Holding / Library Specific Links",
      "repeatable": true
    },
    "982": {
      "label": "Library Specific Subject Headings",
      "repeatable": true
    },
    "983": {
      "label": "Library Specific Classification",
      "repeatable": true
    },
    "984": {
      "label": "Access Numbers",
      "subfields": {
        "2": {
          "label": "internal library number (ILN)"
        },
        "1": {
          "label": "copy sequence number"
        },
        "x": {
          "label": "library/department (only for ill)"
        },
        "a": {
          "repeatable": true,
          "label": "access number (from)"
        },
        "b": {
          "repeatable": true,
          "label": "access number (to)"
        },
        "c": {
          "repeatable": true,
          "label": "volume label"
        }
      }
    }
  }
}
